// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRoROXqBYrxtefiLS32hrKCDJN01nR5EM',
    appId: '1:178292526580:web:5d2893855d73b16d1efda1',
    messagingSenderId: '178292526580',
    projectId: 'dashboard-project-98c28',
    authDomain: 'dashboard-project-98c28.firebaseapp.com',
    storageBucket: 'dashboard-project-98c28.appspot.com',
    measurementId: 'G-EZ7GYF29KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUDi3IzmBNdDfgvcz6hYg0Lp6i5WnX4M',
    appId: '1:178292526580:android:db1b63f8e38e91461efda1',
    messagingSenderId: '178292526580',
    projectId: 'dashboard-project-98c28',
    storageBucket: 'dashboard-project-98c28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkaWNhZui-lrS9yn_WsFgjqTvmJSX6Dc',
    appId: '1:178292526580:ios:9abc682e4fdb08361efda1',
    messagingSenderId: '178292526580',
    projectId: 'dashboard-project-98c28',
    storageBucket: 'dashboard-project-98c28.appspot.com',
    iosBundleId: 'com.example.dashbaordProjectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqkaWNhZui-lrS9yn_WsFgjqTvmJSX6Dc',
    appId: '1:178292526580:ios:9abc682e4fdb08361efda1',
    messagingSenderId: '178292526580',
    projectId: 'dashboard-project-98c28',
    storageBucket: 'dashboard-project-98c28.appspot.com',
    iosBundleId: 'com.example.dashbaordProjectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRoROXqBYrxtefiLS32hrKCDJN01nR5EM',
    appId: '1:178292526580:web:817a16396ff95e8e1efda1',
    messagingSenderId: '178292526580',
    projectId: 'dashboard-project-98c28',
    authDomain: 'dashboard-project-98c28.firebaseapp.com',
    storageBucket: 'dashboard-project-98c28.appspot.com',
    measurementId: 'G-N9M92HRE3J',
  );
}
